name: Deploy MkDocs

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install Material for MkDocs
      run: pip install mkdocs-material
      
    - name: Deploy docs
      run: mkdocs gh-deploy -b org --force
